# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14HZO0MTiUNhOJfuyCFujtkVwKJTzUVoa
"""

size = int(input())
space = [int(item) for item in input().split() ]

num = int(input())
qry = [int(item) for item in input().split()]

count1 = 0
count2 = 0
for val in qry:
  for i in range(size):
    count1+=1
    if(space[i]==val):
      break;
  for j in reversed(range(size)):
    count2+=1
    if(space[j]==val):
      break
print(count1,count2)

