# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AS6kt_4E3wfkX0nF6hs52PSBqwNwpAtM
"""

import math
n = int(input())
r = math.factorial(n)
print(r)
count=0
while(r%10==0):
    r = r//10
    count+=1
print(count)