# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14HZO0MTiUNhOJfuyCFujtkVwKJTzUVoa
"""

size = int(input())
values = [0]*100001
index =1
for item in input().split():
  values[int(item)]=index
  index+=1

num = int(input())

count1 = 0
count2 = 0
queries = [int(items) for items in input().split()]
for val in queries:
  count1+=values[val]
  count2+=size-values[val]+1
print(count1,count2)

