# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrm8-vOJnNKhFZzXQZZOJAnZpemBCpco
"""

code = input()
while(code!='0'):
  code = list(code)
  for i in range(len(code)-1):
    if(code[i+1]=='0'):
      code[i]=code[i]+code[i+1]

  for i in range(len(code)):
    if (code[i]=='00'):
      flag = 0
      break
    elif(int(code[i])>26):
      flag=0
      break
    else:
      flag=1
  rectified = [(code[i])  for i in range(len(code)) if int(code[i])!=0]

  def magic_s(rect):
    result = [0]*(len(rect)-1)
    for i in range(len(rect)-1):
      num = int(rect[i]+rect[i+1])
      if num>=10 and num<=26:
        result[i]=1
    return result
  chunks = magic_s(rectified)

  sum=1
  for i in range(len(rectified)):
    if int(rectified[i])<=26 and int(rectified[i])>0:
      continue
    else:
      sum=0
      break

  def calc(piece):
    size = len(piece)
    result = [0]*size
    for i in reversed(range(size-2)):
      result[i]+=piece[i+2] + result[i+1]
    for(i) in range(size):
      if(piece[i]==0):
        result[i] =0
    return result

  from operator import add
  final = [0]*len(chunks)
  result = chunks
  middle = [1]*len(chunks)
  while (set(middle)!=set(final)):
    middle = calc(chunks)
    result = list(map(add,result,middle))
    chunks = middle

  sum1=0
  for i in range(len(result)):
    sum1+=result[i]
  if(flag):
    print(sum+sum1)
  else:
    print(0)
  code = input()

